package com.xwrokz.Collection;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.function.Predicate;

public class AddAllRunner {

	private static String contains;

	public static void main(String[] args) {
		Collection<String> damsInKarnataka = new ArrayList<String>();
		damsInKarnataka.add("Almatti");
		damsInKarnataka.add("Basava Sagara");
		damsInKarnataka.add("Raja Lakhamagowda");
		damsInKarnataka.add("Renuka Sagara");
		damsInKarnataka.add("Vani Vilasa Sagara");
		damsInKarnataka.add("Upper Tunga");
		damsInKarnataka.add("Bhadra");
		damsInKarnataka.add("Tungabhadra");
		damsInKarnataka.add("Hemavathi Reservoir");
		damsInKarnataka.add("Kabini Reservoir");
		damsInKarnataka.add("Harangi Reservoir");
		damsInKarnataka.add("Krishna Raja Sagara");
		damsInKarnataka.add("Linganamakki");
		damsInKarnataka.add("Chakra Reservoir");
		damsInKarnataka.add("Savehaklu Reservoir");
		damsInKarnataka.add("Mani Reservoir");
		damsInKarnataka.add("Supa");
		damsInKarnataka.add("Kodasalli");
		damsInKarnataka.add("Kadra");
		damsInKarnataka.add("Shanti Sagara");
		damsInKarnataka.add("Karanja" );
		System.out.println("Size of dams in Karnataka : "+damsInKarnataka.size());
		
		Collection<String> damsInKerala = new ArrayList<String>();
		damsInKerala.add("Banasura Sagar");
		damsInKerala.add("Mattupetty");
		damsInKerala.add("Idukki");
		damsInKerala.add("Malampuzha Garden");
		damsInKerala.add("Maniyar");
		damsInKerala.add("Walayar");
		damsInKerala.add("Anathode");
		damsInKerala.add("Anayirangal");
		damsInKerala.add("Aruvikkara");
		damsInKerala.add("Azhutha");
		damsInKerala.add("Bhoothathankettu");
		damsInKerala.add("Chulliyar");
		damsInKerala.add("Chenkulam");
		damsInKerala.add("Cheruthoni");
		damsInKerala.add("Chimmini");
		damsInKerala.add("Erattayar");
		damsInKerala.add("Gavi");
		damsInKerala.add("Idamalayar");
		damsInKerala.add("Kakki");
		damsInKerala.add("Kakkad");
		damsInKerala.add("Kakkayam");
		damsInKerala.add("Kallar");
		damsInKerala.add("Kanjirapuzha");
		damsInKerala.add("Karapuzha");
		damsInKerala.add("Kochu Pamba");
		damsInKerala.add("Kulamavu");
		damsInKerala.add("Kullar");
		damsInKerala.add("Kallarkutty");
		damsInKerala.add("KundalaPambla");
		damsInKerala.add("Ranni-Perinad");
		damsInKerala.add("Mangalam");
		damsInKerala.add("Malampuzha");
		damsInKerala.add("Malankara");
		damsInKerala.add("Mattupetty");
		damsInKerala.add("Meenar -1");
		damsInKerala.add("Meenar -2");
		damsInKerala.add("Meenkara");
		damsInKerala.add("Mullaperiyar");
		damsInKerala.add("Mullakkanam");
		damsInKerala.add("Moozhiyar");
		damsInKerala.add("Narakakkanam");
		damsInKerala.add("Neyyar");
		damsInKerala.add("Pamba");
		damsInKerala.add("Pambla");
		damsInKerala.add("Parakkadavu");
		damsInKerala.add("Pazhassi");
		damsInKerala.add("Peppara");
		damsInKerala.add("Peringalkuthu");
		damsInKerala.add("Perunthenaruvi");
		damsInKerala.add("Peruvannamuzhi");
		damsInKerala.add("Peruvaripallam");
		damsInKerala.add("Peechi");
		damsInKerala.add("Parambikulam");
		damsInKerala.add("Ponmudi");
		damsInKerala.add("Pothundi");
		damsInKerala.add("R. A. Headworks");
		damsInKerala.add("Upper Moozhiyar");
		damsInKerala.add("Sholayar");
		damsInKerala.add("Siruvani");
		damsInKerala.add("Thoonakkadavu");
		damsInKerala.add("Thenmala");
		damsInKerala.add("Urumi 1");
		damsInKerala.add("Urumi 2");
		damsInKerala.add("Vazhani");
		damsInKerala.add("Vellathooval");
		damsInKerala.add("Veluthodu");
		damsInKerala.add("Viripara");
		System.out.println("Size of dams in Kerala : "+damsInKerala.size());
		
		Collection<String> damsInTamilNadu = new ArrayList<String>();
		damsInTamilNadu.add("Aathupalayam");
		damsInTamilNadu.add("Adavinainar");
		damsInTamilNadu.add("Aliyar Reservoir");
		damsInTamilNadu.add("Amaravathi ");
		damsInTamilNadu.add("Anaikuttam");
		damsInTamilNadu.add("Bhavanisagar");
		damsInTamilNadu.add("Gomukhinadhi Reservoir");
		damsInTamilNadu.add("Kalingarayan Anicut");
		damsInTamilNadu.add("Kallanai ");
		damsInTamilNadu.add("Kamaraj Sagar");
		damsInTamilNadu.add("Karuppanadhi");
		damsInTamilNadu.add("Kodaganar");
		damsInTamilNadu.add("Kodiveri");
		damsInTamilNadu.add("Krishnagiri");
		damsInTamilNadu.add("Kunderipallam");
		damsInTamilNadu.add("Kuppanatham");
		damsInTamilNadu.add("Lower Anaicut");
		damsInTamilNadu.add("Manimuthar");
		damsInTamilNadu.add("Manjalar");
		damsInTamilNadu.add("Mettur");
		damsInTamilNadu.add("Mukkadal");
		damsInTamilNadu.add("Nallathangal");
		damsInTamilNadu.add("Orathuppalayam");
		damsInTamilNadu.add("Papanasam");
		damsInTamilNadu.add("Pechiparai Reservoir");
		damsInTamilNadu.add("Perumpallam");
		damsInTamilNadu.add("Perunchani");
		damsInTamilNadu.add("Poigai");
		damsInTamilNadu.add("Sathanur");
		damsInTamilNadu.add("Servalar");
		damsInTamilNadu.add("Shanmuganathi");
		damsInTamilNadu.add("Solaiyar");
		damsInTamilNadu.add("Sothuparai");
		damsInTamilNadu.add("Thirumoorthy");
		damsInTamilNadu.add("Upper Anaicut");
		damsInTamilNadu.add("Vaigai");
		damsInTamilNadu.add("Varattupallam");
		System.out.println("Size of dams in TamilNadu : "+damsInTamilNadu.size());
		
		
		Collection<String> damsInAndhraPradesh = new ArrayList<String>();
		damsInAndhraPradesh.add("Ahobilam / Penna Ahobilam (Dr. K.S.P.A.B.R.) ");
		damsInAndhraPradesh.add("Akkapalem");
		damsInAndhraPradesh.add("Alaganoor");
		damsInAndhraPradesh.add("Ananthasagarm");
		damsInAndhraPradesh.add("Andhra");
		damsInAndhraPradesh.add("Arniar");
		damsInAndhraPradesh.add("Bahuda");
		damsInAndhraPradesh.add("Bhairavanithippa");
		damsInAndhraPradesh.add("Bhupathipalem ");
		damsInAndhraPradesh.add("Buggavagu");
		damsInAndhraPradesh.add("Buggavanka");
		damsInAndhraPradesh.add("Bukkapatnam");
		damsInAndhraPradesh.add("Chagallu Barrage");
		damsInAndhraPradesh.add("Cheyyeru / Annamayya");
		damsInAndhraPradesh.add("Chinnarayaswamy Gudi /Chennaraya ");
		damsInAndhraPradesh.add("Chintakuntavagu");
		damsInAndhraPradesh.add("Chitravathi");
		damsInAndhraPradesh.add("Cumbum");
		damsInAndhraPradesh.add("Dharmavaram ");
		damsInAndhraPradesh.add("Donkarai ( S.H.E.S)");
		damsInAndhraPradesh.add("Eguva Thamballa Palli - Cheruvu");
		damsInAndhraPradesh.add("Forebay Lower Sileru ( S.H.E.S) ");
		damsInAndhraPradesh.add("Gajuladinne (Sanjeevaiah Sagar)");
		damsInAndhraPradesh.add("Gandicheruvu (Dist-Prakasam)");
		damsInAndhraPradesh.add("Gandipalem /Pcr Gandipalem ");
		damsInAndhraPradesh.add("Ghambiramgedda ");
		damsInAndhraPradesh.add("Gooty Tank");
		damsInAndhraPradesh.add("Gorakallu");
		damsInAndhraPradesh.add("Gundlakamma");
		damsInAndhraPradesh.add("Gundlamotu ");
		damsInAndhraPradesh.add("Guntawada Main");
		damsInAndhraPradesh.add("Haresamudram Big");
		damsInAndhraPradesh.add("Hiramandalam ");
		damsInAndhraPradesh.add("Jajigedda ");
		damsInAndhraPradesh.add("Jalakanur");
		damsInAndhraPradesh.add("Jalleru ");
		damsInAndhraPradesh.add("Janjavathi ");
		damsInAndhraPradesh.add("Kakarla");
		damsInAndhraPradesh.add("Kalangi");
		damsInAndhraPradesh.add("Kalyani");
		damsInAndhraPradesh.add("Kampasamudram New ");
		damsInAndhraPradesh.add("Kandaleru ");
		damsInAndhraPradesh.add("Kanigiri ");
		damsInAndhraPradesh.add("Konam ");
		damsInAndhraPradesh.add("Kovvadakalva");
		damsInAndhraPradesh.add("Kumili");
		damsInAndhraPradesh.add("Kushavathi");
		damsInAndhraPradesh.add("Lower Sagileru");
		damsInAndhraPradesh.add("Madakasira");
		damsInAndhraPradesh.add("Maddigedda");
		damsInAndhraPradesh.add("Madduvalasa ");
		damsInAndhraPradesh.add("Mallimadugu");
		damsInAndhraPradesh.add("Mid-Pennar");
		damsInAndhraPradesh.add("Mopadu");
		damsInAndhraPradesh.add("Mararipalli ");
		damsInAndhraPradesh.add("Mylavaram");
		damsInAndhraPradesh.add("Nakkalagandi");
		damsInAndhraPradesh.add("Narayanapuram");
		damsInAndhraPradesh.add("Nellore ");
		damsInAndhraPradesh.add("Paleru ,Owk ");
		damsInAndhraPradesh.add("Pampa");
		damsInAndhraPradesh.add("Peddabadava, Tulasikrishan");
		damsInAndhraPradesh.add("Pincha");
		damsInAndhraPradesh.add("Pittakayagulla");
		damsInAndhraPradesh.add("Polavaram");
		damsInAndhraPradesh.add("Raiwada");
		damsInAndhraPradesh.add("Rallapadu ");
		damsInAndhraPradesh.add("SPVBS ");
		damsInAndhraPradesh.add("Sadasivakona");
		damsInAndhraPradesh.add("Siddalagandi");
		damsInAndhraPradesh.add("Surampalem ");
		damsInAndhraPradesh.add("Thammileru");
		damsInAndhraPradesh.add("Thatipudi");
		damsInAndhraPradesh.add("Upper Pennar ");
		damsInAndhraPradesh.add("Velugodu ");
		damsInAndhraPradesh.add("Veligonda ");
		damsInAndhraPradesh.add("Vengalaraya Sagar ");
		damsInAndhraPradesh.add("Vottigadda");
		damsInAndhraPradesh.add("Vanaka Badigedda");
		damsInAndhraPradesh.add("Yeddula Eswaraiah GandiKoata ");
		damsInAndhraPradesh.add("Yeleru ");
		damsInAndhraPradesh.add("Yerrakalva ");
		damsInAndhraPradesh.add("Yogivemana");
		damsInAndhraPradesh.add("Zurreru");
		System.out.println("Size of dams in AndhraPradesh : "+damsInAndhraPradesh.size());
		
		Collection<String> damsInTelangana = new ArrayList<String>();
		damsInTelangana.add("Ada Village - Peddavagu");
		damsInTelangana.add("Akkampalli");
		damsInTelangana.add("Bandlavagu, Kukkalgudur");
		damsInTelangana.add("Bazarthathnur");
		damsInTelangana.add("Bethampudi");
		damsInTelangana.add("Bheemanpally");
		damsInTelangana.add("Boath");
		damsInTelangana.add("Boggulavagu");
		damsInTelangana.add("Chelamelavagu");
		damsInTelangana.add("Choutaplly Hanuman Reddy Lift");
		damsInTelangana.add("Dantakani Cheruvu");
		damsInTelangana.add("Devathlacheru, Yeldurthy");
		damsInTelangana.add("Dindi");
		damsInTelangana.add("Fox Sagar, Jeedimetla ");
		damsInTelangana.add("Gidda Cheru, Yellareddypet (V)");
		damsInTelangana.add("Gudipalligattu");
		damsInTelangana.add("Gujjulavagu , Gandhari ");
		damsInTelangana.add("Gundetivagu Cheroo, Reddygudem(V)");
		damsInTelangana.add("Gundlavagu");
		damsInTelangana.add("Himayat Sagar");
		damsInTelangana.add("Indirammasagar, Anajpur");
		damsInTelangana.add("Jutepally");
		damsInTelangana.add("Kaddam (K.N.R.)");
		damsInTelangana.add("Kesavari Samudram");
		damsInTelangana.add("Kinnerasani");
		damsInTelangana.add("Koil Sagar");
		damsInTelangana.add("Komaram Bheem");
		damsInTelangana.add("Komsettipally");
		damsInTelangana.add("Kothacheru");
		damsInTelangana.add("Kotipally Vagu");
		damsInTelangana.add("Lakhnapur");
		damsInTelangana.add("Lakhnavaram");
		damsInTelangana.add("Lankasagar");
		damsInTelangana.add("Adloor Yellareddy");
		damsInTelangana.add("Bibipet Dam");
		damsInTelangana.add("Brahmanpally");
		damsInTelangana.add("Dharmaraopet");
		damsInTelangana.add("Garepally(V), Sultanabad(M)");
		damsInTelangana.add("Garla");
		damsInTelangana.add("Husnabad");
		damsInTelangana.add("Indalwai(V)");
		damsInTelangana.add(" Jangampally");
		damsInTelangana.add("Kachapur");
		damsInTelangana.add("Malikacheru, Mamdabad");
		damsInTelangana.add("Mallammacheruvu Saralnagar");
		damsInTelangana.add("Malluruvagu");
		damsInTelangana.add("Medi Cheru");
		damsInTelangana.add("Mid Manair");
		damsInTelangana.add("Mukkamamidi");
		damsInTelangana.add("Mulavagu");
		damsInTelangana.add("Nagarjuna Sagar");
		damsInTelangana.add("Musi");
		damsInTelangana.add("Nagarjunasagar Tai");
		damsInTelangana.add("Nallacheru, Irvin");
		damsInTelangana.add("Nallavagu");
		damsInTelangana.add("Namaz Cheru, Gambhiraopet (V)");
		damsInTelangana.add("Nandivagu , Kasula");
		damsInTelangana.add("Neelwai");
		damsInTelangana.add("New , Bellempally");
		damsInTelangana.add("Kothur Dam");
		damsInTelangana.add("Nizam Sagar");
		damsInTelangana.add("Ookachettivagu");
		damsInTelangana.add("Oora Cheru,Yadaram");
		damsInTelangana.add("Osman Sagar");
		damsInTelangana.add("Palair");
		damsInTelangana.add("Palemvagu");
		damsInTelangana.add("Pedda Cheru");
		damsInTelangana.add("Peddarayanicheru");
		damsInTelangana.add("Peddavagu-Jagannathpur");
		damsInTelangana.add("Pocharam");
		damsInTelangana.add("Priyadarshini Jurala");
		damsInTelangana.add("Rai Rao Cheru");
		damsInTelangana.add("Ramadugu");
		damsInTelangana.add("Ramappa");
		damsInTelangana.add("Salivagu");
		damsInTelangana.add("Sangambanda");
		damsInTelangana.add("Sarala Sagar");
		damsInTelangana.add("Sathanala");
		damsInTelangana.add("Shanigram");
		damsInTelangana.add("Singhabhoopalem");
		damsInTelangana.add("Singur");
		damsInTelangana.add("Pochampad");
		damsInTelangana.add("Srisailam (N.S.R.S.P)");
		damsInTelangana.add("Suryanarayanacheru");
		damsInTelangana.add("Swarna");
		damsInTelangana.add("Taliperu");
		damsInTelangana.add("Upper Manair");
		damsInTelangana.add("Vattivagu");
		damsInTelangana.add("Vemular");
		damsInTelangana.add("Wyra");
		damsInTelangana.add("Yellur");
		damsInTelangana.add("Yenukunta");
		damsInTelangana.add("Yerravagu");
		damsInTelangana.add("Zildartippa");
		System.out.println("Size of dams in Telangana : "+damsInTelangana.size());
		
		Collection<String> damsInGoa = new ArrayList<String>();
		damsInGoa.add("Anjunam");
		damsInGoa.add("M.I.");
		damsInGoa.add("Salaulim");
		System.out.println("Size of dams in Goa : "+damsInGoa.size());
		
		Collection<String> damsInGujarat = new ArrayList<String>();
		damsInGujarat.add("Aamli Chharchhoda");
		damsInGujarat.add("Abhalwad");
		damsInGujarat.add("Adhia");
		damsInGujarat.add("Adhochhani");
		damsInGujarat.add("Adhoi- I");
		damsInGujarat.add("Adpur");
		damsInGujarat.add("Advana");
		damsInGujarat.add("Aji I");
		damsInGujarat.add("Aji II");
		damsInGujarat.add("Aji III");
		damsInGujarat.add("Aji IV");
		damsInGujarat.add("Ajwa");
		damsInGujarat.add("Alan Sagar");
		damsInGujarat.add("Amalwant");
		damsInGujarat.add("Ambajal");
		damsInGujarat.add("Ambani Khodiar");
		damsInGujarat.add("Ambaradi");
		damsInGujarat.add("Bagad");
		damsInGujarat.add("Badi-Padva");
		damsInGujarat.add("Bandhara");
		damsInGujarat.add("Dantiwada");
		damsInGujarat.add("Kadana");
		damsInGujarat.add("Kakari Mahudi");
		damsInGujarat.add("Kelia");
		damsInGujarat.add("Khambhala");
		damsInGujarat.add("Mamuara");
		damsInGujarat.add("Mazam");
		damsInGujarat.add("Megal Tr");
		damsInGujarat.add("Meshwo");
		damsInGujarat.add("Mevasa");
		damsInGujarat.add("Mitti");
		damsInGujarat.add("Moj");
		damsInGujarat.add("Nara");
		damsInGujarat.add("Nyari- I");
		damsInGujarat.add("Panam");
		damsInGujarat.add("Sabarmati");
		damsInGujarat.add("Sardar Sarover Gujarat");
		damsInGujarat.add("Shetrunji");
		damsInGujarat.add("Sukhbhadar");
		damsInGujarat.add("Surajwadi");
		damsInGujarat.add("Ukai");
		damsInGujarat.add("Uben");
		damsInGujarat.add("Turkha");
		damsInGujarat.add("Zinzari");
		damsInGujarat.add("sardar sarover saddle");
		damsInGujarat.add("shell Dedumaal");
		damsInGujarat.add("Zar");
		damsInGujarat.add("Zanzarwa");
		damsInGujarat.add("Zalu");
		damsInGujarat.add("Zakashiya");
		damsInGujarat.add("Watrak");
		damsInGujarat.add("Wanklaeswar-Bhey");
		damsInGujarat.add("Wandh-Mandvi");
		damsInGujarat.add("Wandh");
		damsInGujarat.add("Wadhwan Jojwa");
		damsInGujarat.add("Vrajmi");
		damsInGujarat.add("Virpur");
		damsInGujarat.add("Virani");
		damsInGujarat.add("Vijaysagar");
		damsInGujarat.add("Vijarkhi");
		damsInGujarat.add("Veri");
		damsInGujarat.add("Ver II");
		damsInGujarat.add("Veradi -II");
		damsInGujarat.add("Vali");
		damsInGujarat.add("Valavad");
		damsInGujarat.add("Vanala");
		damsInGujarat.add("Vansiali");
		damsInGujarat.add("Vagadi");
		damsInGujarat.add("Vagas");
		damsInGujarat.add("Vagdokyari");
		damsInGujarat.add("Vaghvadarada");
		damsInGujarat.add("Vaidy");
		damsInGujarat.add("Thoralia Mi");
		damsInGujarat.add("Toda");
		damsInGujarat.add("Trivni-Tranga");
		damsInGujarat.add("Thikariyala");
		damsInGujarat.add("Thol");
		damsInGujarat.add("Tara-Manjal");
		damsInGujarat.add("Targol ");
		damsInGujarat.add("Thanagalol");
		damsInGujarat.add("Tharawada");
		damsInGujarat.add("Sod Vadar");
		damsInGujarat.add("Sogth");
		damsInGujarat.add("Solsandha");
		damsInGujarat.add("Sonmati");
		damsInGujarat.add("Sonwadi");
		damsInGujarat.add("Shiney");
		damsInGujarat.add("Shingoda");
		damsInGujarat.add("Shivlakha");
		damsInGujarat.add("Sidhumber");
		damsInGujarat.add("Singla");
		damsInGujarat.add("Singor");
		damsInGujarat.add("Rojki");
		damsInGujarat.add("Rudramata");
		System.out.println("Size of dams in Gujarat : "+damsInGujarat.size());
		
		Collection<String> damsInChhattisgarh = new ArrayList<String>();
		damsInChhattisgarh.add("Tandula");
		damsInChhattisgarh.add("Dudhawa");
		damsInChhattisgarh.add("Gangrel");
		damsInChhattisgarh.add("Kherkatta Reservoir");
		damsInChhattisgarh.add("Murrum Silli");
		damsInChhattisgarh.add("Sondur");
		damsInChhattisgarh.add("Hasdeo Bango");
		damsInChhattisgarh.add("Adpather");
		damsInChhattisgarh.add("Agariya");
		damsInChhattisgarh.add("Ajabnagar");
		damsInChhattisgarh.add("Usaritola");
		damsInChhattisgarh.add("Tanjara");
		damsInChhattisgarh.add("Thakurdiya");
		damsInChhattisgarh.add("Tungal");
		System.out.println("Size of dams in Chhattisgarh : "+damsInChhattisgarh.size());
		
		Collection<String> damsInArunachalPradesh=new ArrayList<String>();
		damsInArunachalPradesh.add("Ranganadi Dam");
		damsInArunachalPradesh.add("Subansiri Lower HE Dam");
		System.out.println("Size of dams in ArunachalPradesh : "+damsInArunachalPradesh.size());
		
		Collection<String> damsInNagaland=new ArrayList<String>();
		damsInNagaland.add("Hep Dam");
		System.out.println("Size of dams in Nagaland : "+damsInNagaland.size());
		
		Collection<String> damsInManipur=new ArrayList<String>();
		damsInManipur.add("Khoupum Dam");
		damsInManipur.add("Khuga Dam");
		damsInManipur.add("Singda Dam");
		damsInManipur.add("Thoubal Dam");
		System.out.println("Size of dams in Manipur : "+damsInManipur.size());
		
		Collection<String> damsInMizoram=new ArrayList<String>();
		damsInMizoram.add("Serlui B Dam ");
		damsInMizoram.add("Tuirial Dam");
		System.out.println("Size of dams in Mizoram : "+damsInMizoram.size());
		
		Collection<String> damsInAssam=new ArrayList<String>();
		damsInAssam.add("Karbi Langpi Dam");
		damsInAssam.add("Umrong Dam");
		System.out.println("Size of dams in Assam : "+damsInAssam.size());
		
		Collection<String> damsInMeghalaya=new ArrayList<String>();
		damsInMeghalaya.add("Khandong Dam");
		damsInMeghalaya.add("Kyrdemkulai Dam");
		damsInMeghalaya.add("Mawphlang Dam");
		damsInMeghalaya.add("Myntdu-Leshka Dam");
		damsInMeghalaya.add("Nongkhyllem Dam");
		damsInMeghalaya.add("Umiam Dam");
		damsInMeghalaya.add("Umtru Dam");
		System.out.println("Size of dams in Meghalaya : "+damsInMeghalaya.size());
		
		Collection<String> damsInTripura=new ArrayList<String>();
		damsInTripura.add("Gumti Hydro Dam");
		System.out.println("Size of dams in Tripura : "+damsInTripura.size());
		
		Collection<String> damsInWestBengal=new ArrayList<String>();
		damsInWestBengal.add("Bakreshwar Dam");
		damsInWestBengal.add("Bandhu Dam");
		damsInWestBengal.add("Bara Mandira Dam");
		damsInWestBengal.add("Barabhum Dam");
		damsInWestBengal.add("Beko Dam");
		damsInWestBengal.add("Dangrajhore Dam");
		damsInWestBengal.add("Dimu Dam");
		damsInWestBengal.add("Futiary Dam");
		damsInWestBengal.add("Golamarajore Dam");
		damsInWestBengal.add("Hanumata Dam");
		damsInWestBengal.add("Hinglow Irrigation Scheme Dam");
		damsInWestBengal.add("Kangsabati Kumari Dam");
		damsInWestBengal.add("Kanjan Dam");
		damsInWestBengal.add("Karrior Dam");
		damsInWestBengal.add("Khairabera Dam");
		damsInWestBengal.add("Kumari Dam");
		damsInWestBengal.add("Lipania Dam");
		damsInWestBengal.add("Lower : PPSP Dam");
		damsInWestBengal.add("Moutorejore Dam");
		damsInWestBengal.add("Muruguma Dam");
		damsInWestBengal.add("Nachan Irri Scheme Dam");
		damsInWestBengal.add("Paraga Irri. Scheme Dam");
		damsInWestBengal.add("Patloi Dam");
		damsInWestBengal.add("Ramchandrapur Dam");
		damsInWestBengal.add("Rupai Dam");
		damsInWestBengal.add("Saharajore Irri Scheme Dam");
		damsInWestBengal.add("Sali Dam");
		damsInWestBengal.add("Taragonia Irri Scheme Dam");
		damsInWestBengal.add("Tatko Dam");
		damsInWestBengal.add("Teesta-III Lower Dam");
		damsInWestBengal.add("Teesta-IV Lower Dam");
		damsInWestBengal.add("Turga Irri Scheme Dam");
		damsInWestBengal.add("Upper Dam: PPSP");
		System.out.println("Size of dams in WestBengal : "+damsInWestBengal.size());
		
		Collection<String> damsInSikkim=new ArrayList<String>();
		damsInSikkim.add("Rangit III Dam");
		damsInSikkim.add("Rangpo Dam");
		damsInSikkim.add("Rongli Dam");
		damsInSikkim.add("Teesta -V (NHPC) Dam");
		damsInSikkim.add("Teesta-III Dam");
		damsInSikkim.add("Teesta-IV Dam");
		System.out.println("Size of dams in Sikkim : "+damsInSikkim.size());
		
		Collection<String> damsInBihar=new ArrayList<String>();
		damsInBihar.add("Ajan Dam");
		damsInBihar.add("Amrity Dam");
		damsInBihar.add("Badua Dam");
		damsInBihar.add("Barnar Dam");
		damsInBihar.add("Baskund Dam");
		damsInBihar.add("Belharna Dam");
		damsInBihar.add("Bilasi Dam");
		damsInBihar.add("Chandan Dam");
		damsInBihar.add("Durgawati Dam");
		damsInBihar.add("Gaighat Dam");
		damsInBihar.add("Jalkund Dam");
		damsInBihar.add("Job Dam");
		damsInBihar.add("Kailash Ghati Dam");
		damsInBihar.add("Khargpur Lake Dam");
		damsInBihar.add("Kohira Dam");
		damsInBihar.add("Kolmahadeo Dam");
		damsInBihar.add("Morwy Dam");
		damsInBihar.add("Nagi Dam");
		damsInBihar.add("Nakti Dam");
		damsInBihar.add("Orhni Dam");
		damsInBihar.add("Phulwaria Dam");
		damsInBihar.add("Sindhwarni Dam");
		damsInBihar.add("Srikhandi Dam");
		damsInBihar.add("Upper Kiul Dam");
		System.out.println("Size of dams in Bihar : "+damsInBihar.size());
		
		Collection<String> damsInJharkhand=new ArrayList<String>();
		damsInJharkhand.add("Amanat Dam");
		damsInJharkhand.add("Anjanwa Dam");
		damsInJharkhand.add("Anraj Dam");
		damsInJharkhand.add("Baksa/Buksa Dam");
		damsInJharkhand.add("Bandha Dam");
		damsInJharkhand.add("Baranadi Dam");
		damsInJharkhand.add("Barhi Dam");
		damsInJharkhand.add("Basuki Dam");
		damsInJharkhand.add("Batane Dam");
		damsInJharkhand.add("Batre Dam");
		damsInJharkhand.add("Bhairwa Dam");
		damsInJharkhand.add("Bhavnikhand Khand Dam");
		damsInJharkhand.add("Bhutanduba Dam");
		damsInJharkhand.add("Bucha Opa Dam");
		damsInJharkhand.add("Burhai Dam");
		damsInJharkhand.add("Chandil Dam");
		damsInJharkhand.add("Chatania Ghat Dam");
		damsInJharkhand.add("Chinda Dam");
		damsInJharkhand.add("Chirka Dam");
		damsInJharkhand.add("Danro Dam");
		damsInJharkhand.add("Dhankai Dam");
		damsInJharkhand.add("Dhansingtoli Dam");
		damsInJharkhand.add("Dhulki Dam");
		damsInJharkhand.add("Diggalpahari Dam");
		damsInJharkhand.add("Garhi Dam");
		damsInJharkhand.add("Getalsud Dam");
		damsInJharkhand.add("Ghaghra Dam");
		damsInJharkhand.add("Gonda Dam");
		damsInJharkhand.add("Hatia Dam");
		damsInJharkhand.add("Hiru Dam");
		damsInJharkhand.add("Icha Dam");
		damsInJharkhand.add("Jaipur Dam");
		damsInJharkhand.add("Jamunia Dam");
		damsInJharkhand.add("Jenasai Dam");
		damsInJharkhand.add("Jharjhara Dam");
		damsInJharkhand.add("Kanhar Dam");
		damsInJharkhand.add("Kans Dam");
		damsInJharkhand.add("Kansjore Dam");
		damsInJharkhand.add("Karawani Dam");
		damsInJharkhand.add("Katri Dam");
		damsInJharkhand.add("Kesho Dam");
		damsInJharkhand.add("Khudia Dam");
		damsInJharkhand.add("Konar Dam");
		damsInJharkhand.add("Larwa Dam");
		damsInJharkhand.add("Latratu Dam");
		damsInJharkhand.add("Left Banki Dam");
		damsInJharkhand.add("Lorgara Dam");
		damsInJharkhand.add("Lotia Dam");
		damsInJharkhand.add("Maithon Dam");
		damsInJharkhand.add("Malay Dam");
		damsInJharkhand.add("Masanjor JH Dam");
		damsInJharkhand.add("Masaria Dam");
		damsInJharkhand.add("Murahir Dam");
		damsInJharkhand.add("Nakti Dam");
		damsInJharkhand.add("Nalkari Dam");
		damsInJharkhand.add("Nandini Dam");
		damsInJharkhand.add("North Koel Dam");
		damsInJharkhand.add("Palna Dam");
		damsInJharkhand.add("Panchat Hill Dam");
		damsInJharkhand.add("Panchkhero Dam");
		damsInJharkhand.add("Pandarwa Dam");
		damsInJharkhand.add("Paras Dam");
		damsInJharkhand.add("Punasi Dam");
		damsInJharkhand.add("Raisa Dam");
		damsInJharkhand.add("Ramrekha Dam");
		damsInJharkhand.add("Salaiya Dam");
		damsInJharkhand.add("Satpotka Dam");
		damsInJharkhand.add("Sitaram Pur Dam");
		damsInJharkhand.add("Sonua Dam");
		damsInJharkhand.add("Sudhari Nala Dam");
		damsInJharkhand.add("Sugathan Dam");
		damsInJharkhand.add("Sukri Dam");
		damsInJharkhand.add("Sunder Dam");
		damsInJharkhand.add("Surangi Dam");
		damsInJharkhand.add("Suryodi Dam");
		damsInJharkhand.add("Tahlay Dam");
		damsInJharkhand.add("Tajna Dam");
		damsInJharkhand.add("Tapkara Dam");
		damsInJharkhand.add("Temrain Dam");
		damsInJharkhand.add("Tenughat Dam");
		damsInJharkhand.add("Tilaiya Dam");
		damsInJharkhand.add("Torai Dam");
		damsInJharkhand.add("Torlow Dam");
		damsInJharkhand.add("Upper Shankh Dam");
		System.out.println("Size of dams in Jharkhand : "+damsInJharkhand.size());
		
		Collection<String> damsInOdisha=new ArrayList<String>();
		damsInOdisha.add("Alubani");
		damsInOdisha.add("Aradei");
		damsInOdisha.add("Arikul");
		damsInOdisha.add("Badabandha ");
		damsInOdisha.add("Badanalla");
		damsInOdisha.add("Badjore ");
		damsInOdisha.add("Baghalati ");
		damsInOdisha.add("Baghjharan ");
		damsInOdisha.add("Baghua ");
		damsInOdisha.add("Baghua (MI) ");
		damsInOdisha.add("Balaskumpa");
		damsInOdisha.add("Balimela");
		damsInOdisha.add("Bankabal ");
		damsInOdisha.add("Banksal");
		damsInOdisha.add("Baura ");
		damsInOdisha.add("Bautia");
		damsInOdisha.add("Bedapada");
		damsInOdisha.add("Behera");
		damsInOdisha.add("Benikpur");
		damsInOdisha.add("Bhagirijhala ");
		damsInOdisha.add("Bhallugahi");
		damsInOdisha.add("Bhaluguda");
		damsInOdisha.add("Bhanjanagar");
		damsInOdisha.add("Bhaskel");
		damsInOdisha.add("Bhatrajore");
		damsInOdisha.add("Bhetabar");
		damsInOdisha.add("Bhitiri Bediguda");
		damsInOdisha.add("Budhabudiani");
		damsInOdisha.add("Chhamundia");
		damsInOdisha.add("Chhatenjore");
		damsInOdisha.add("Chheligada");
		damsInOdisha.add("Dadara Ghati");
		damsInOdisha.add("Daha(OD)");
		damsInOdisha.add("Damsal");
		damsInOdisha.add("Dasamanthapur");
		damsInOdisha.add("Debijharan");
		damsInOdisha.add("Deo(OD)");
		damsInOdisha.add("Deojharan");
		damsInOdisha.add("Deras");
		damsInOdisha.add("Derjang");
		damsInOdisha.add("Dhanei");
		damsInOdisha.add("Dhulipaunsia");
		damsInOdisha.add("Domkutch");
		damsInOdisha.add("Dumerbahal");
		damsInOdisha.add("Gaikhai(Minor)");
		damsInOdisha.add("Ganianalla");
		damsInOdisha.add("Garh");
		damsInOdisha.add("Gayapathar");
		damsInOdisha.add("Ghagara");
		damsInOdisha.add("Ghatakeswar");
		damsInOdisha.add("Ghodahada");
		damsInOdisha.add("Gohira");
		damsInOdisha.add("Goibali");
		damsInOdisha.add("Gundurapasi");
		damsInOdisha.add("Gurlijore");
		damsInOdisha.add("HATIANALLA M.I.P");
		damsInOdisha.add("Hadua ");
		damsInOdisha.add("Haguri ");
		damsInOdisha.add("Haladia");
		damsInOdisha.add("Hanumantia ");
		damsInOdisha.add("Harabhangi");
		damsInOdisha.add("Hariharjore");
		damsInOdisha.add("Haripur");
		damsInOdisha.add("Hirakud");
		damsInOdisha.add("Indrawati");
		damsInOdisha.add("Jagadala");
		damsInOdisha.add("Jaigarh");
		damsInOdisha.add("Jalaput");
		damsInOdisha.add("Jambhira");
		damsInOdisha.add("Jamboonala ");
		damsInOdisha.add("Jamuna Bundha");
		damsInOdisha.add("Jaunria");
		damsInOdisha.add("Jharanai ");
		damsInOdisha.add("Jharbandha ");
		damsInOdisha.add("Jhumuka ");
		damsInOdisha.add("Jodabadia ");
		damsInOdisha.add("Kakudajodi");
		damsInOdisha.add("Kalakala");
		damsInOdisha.add("Kalijodi ");
		damsInOdisha.add("Kalo");
		damsInOdisha.add("Kangani");
		damsInOdisha.add("Kanheinalla ");
		damsInOdisha.add("Kanjhari");
		damsInOdisha.add("Kansabansa ");
		damsInOdisha.add("Kansbahal ");
		damsInOdisha.add("Kanteijhara ");
		damsInOdisha.add("Kantesir ");
		damsInOdisha.add("Kanupur");
		damsInOdisha.add("Kapur");
		damsInOdisha.add("Karada");
		damsInOdisha.add("Karanjkote ");
		damsInOdisha.add("Khadakhai");
		damsInOdisha.add("Khajuria ");
		damsInOdisha.add("Khandijharan");
		damsInOdisha.add("Khasbahal");
		damsInOdisha.add("Khuntapada");
		damsInOdisha.add("Kiajhar ");
		damsInOdisha.add("Kodabhal");
		damsInOdisha.add("Kodigam");
		damsInOdisha.add("Konheimunda");
		damsInOdisha.add("Koska");
		damsInOdisha.add("Kuanria");
		damsInOdisha.add("Kukurpeta");
		damsInOdisha.add("Kumbho");
		damsInOdisha.add("Kureijodi");
		damsInOdisha.add("Kusunpur");
		damsInOdisha.add("Laigam");
		damsInOdisha.add("Lakhaparbat");
		damsInOdisha.add("Laupal");
		damsInOdisha.add("Laxmipur");
		damsInOdisha.add("Liar");
		damsInOdisha.add("Lower Indra");
		damsInOdisha.add("Lower Suktal");
		damsInOdisha.add("Magara");
		damsInOdisha.add("Maharanisagar");
		damsInOdisha.add("Mahendratanaya");
		damsInOdisha.add("Mahisanalla");
		damsInOdisha.add("Malakangiri");
		damsInOdisha.add("Mandira");
		damsInOdisha.add("Manjhor");
		damsInOdisha.add("Marudi");
		damsInOdisha.add("Masina");
		damsInOdisha.add("Mathan Pal");
		damsInOdisha.add("Mathili");
		damsInOdisha.add("Muran");
		damsInOdisha.add("Nesa");
		damsInOdisha.add("Nimajhar Mip");
		damsInOdisha.add("Padampur");
		damsInOdisha.add("Paitagam");
		damsInOdisha.add("Panaskhal");
		damsInOdisha.add("Pani-Pailla");
		damsInOdisha.add("Pansapal");
		damsInOdisha.add("Parhal");
		damsInOdisha.add("Paunsia");
		damsInOdisha.add("Pilasalki");
		damsInOdisha.add("Pipal");
		damsInOdisha.add("Pitamahal");
		damsInOdisha.add("Podagada");
		damsInOdisha.add("Pokharia");
		damsInOdisha.add("Pratappur");
		damsInOdisha.add("Pujiladu");
		damsInOdisha.add("Raghubeda");
		damsInOdisha.add("Raghunath Sagar");
		damsInOdisha.add("Raijharan");
		damsInOdisha.add("Ramaguda");
		damsInOdisha.add("Ramiala");
		damsInOdisha.add("Randa");
		damsInOdisha.add("Remal");
		damsInOdisha.add("Rengali");
		damsInOdisha.add("Ret");
		damsInOdisha.add("Rissia");
		damsInOdisha.add("Rukura");
		damsInOdisha.add("Rungaon");
		damsInOdisha.add("Saipala");
		damsInOdisha.add("Salandi");
		damsInOdisha.add("Salia");
		damsInOdisha.add("Sanasialinai");
		damsInOdisha.add("Sanmachhakandana");
		damsInOdisha.add("Sapua");
		damsInOdisha.add("Sarapa");
		damsInOdisha.add("Saraphgarh");
		damsInOdisha.add("Satiguda");
		damsInOdisha.add("Sendhie");
		damsInOdisha.add("Soroda");
		damsInOdisha.add("Suhagi");
		damsInOdisha.add("Sunaghai");
		damsInOdisha.add("Sunamuhin");
		damsInOdisha.add("Sundar");
		damsInOdisha.add("Sunei");
		damsInOdisha.add("Talasara");
		damsInOdisha.add("Talkhol");
		damsInOdisha.add("Tangarakana");
		damsInOdisha.add("Telengiri");
		damsInOdisha.add("Tenar");
		damsInOdisha.add("Tikarpada");
		damsInOdisha.add("Tilipada");
		damsInOdisha.add("Titilagarh");
		damsInOdisha.add("Upper Jonk");
		damsInOdisha.add("Upper Kolab");
		damsInOdisha.add("Upper Lanth");
		damsInOdisha.add("Upper Suktel");
		System.out.println("Size of dams in Odisha : "+damsInOdisha.size());
		
		Collection<String> damsInJammuKashmir = new ArrayList<String>();
		damsInJammuKashmir.add("Baglihar");
		damsInJammuKashmir.add("Dulhasti");
		damsInJammuKashmir.add("Kishenganga");
		damsInJammuKashmir.add("Nimoo Bazgo ");
		damsInJammuKashmir.add("Niu Karewa Storage Yusmarg");
		damsInJammuKashmir.add("Pakal Dul");
		damsInJammuKashmir.add("Salal");
		damsInJammuKashmir.add("Sewa St II");
		damsInJammuKashmir.add("Uri-II");
		System.out.println("Size of dams in JammuKashmir : "+damsInJammuKashmir.size());

		Collection<String> damsInHimachalPradesh = new ArrayList<String>();
		damsInHimachalPradesh.add("Baira Siul");
		damsInHimachalPradesh.add("Bassi");
		damsInHimachalPradesh.add("Bhakra");
		damsInHimachalPradesh.add("Chamera I");
		damsInHimachalPradesh.add("Chamera II");
		damsInHimachalPradesh.add("Chamera III");
		damsInHimachalPradesh.add("Karchham-Wangtoo");
		damsInHimachalPradesh.add("Kol");
		damsInHimachalPradesh.add("Largi");
		damsInHimachalPradesh.add("Malana I");
		damsInHimachalPradesh.add("Nathpa Jhakri");
		damsInHimachalPradesh.add("Pandoh");
		damsInHimachalPradesh.add("Parbati - III");
		damsInHimachalPradesh.add("Parbati II ");
		damsInHimachalPradesh.add("Pong ");
		damsInHimachalPradesh.add("Sawra- Kuddu");
		System.out.println("Size of dams in HimachalPradesh : "+damsInHimachalPradesh.size());

		Collection<String> damsInPunjab = new ArrayList<String>();
		damsInPunjab.add("Chohal");
		damsInPunjab.add("Damsal");
		damsInPunjab.add("Dholbaha");
		damsInPunjab.add("Jainti");
		damsInPunjab.add("Janauri");
		damsInPunjab.add("Maili");
		damsInPunjab.add("Mirzapur ");
		damsInPunjab.add("Patiari");
		damsInPunjab.add("Perch");
		damsInPunjab.add("Ranjit Sagar");
		damsInPunjab.add("Saleran ");
		damsInPunjab.add("Shahpur Kandi");
		damsInPunjab.add("Siswan ");
		damsInPunjab.add("Thana");
		System.out.println("Size of dams in Punjab : "+damsInPunjab.size());

		Collection<String> damsInHaryana = new ArrayList<String>();
		damsInHaryana.add("kaushalya");
		System.out.println("Size of dams in Haryana : "+damsInHaryana.size());

		Collection<String> damsInUttarakhand = new ArrayList<String>();
		damsInUttarakhand.add("Baigul");
		damsInUttarakhand.add("Baur");
		damsInUttarakhand.add("Bhimtal");
		damsInUttarakhand.add("Dhauliganga");
		damsInUttarakhand.add("Dhora");
		damsInUttarakhand.add("Haripura");
		damsInUttarakhand.add("Ichari");
		damsInUttarakhand.add("Jamrani");
		damsInUttarakhand.add("Koteshwar");
		damsInUttarakhand.add("Lakhwar");
		damsInUttarakhand.add("Maneri");
		damsInUttarakhand.add("Nanak Sagar");
		damsInUttarakhand.add("Ramganga");
		damsInUttarakhand.add("Tehri");
		damsInUttarakhand.add("Tumaria");
		System.out.println("Size of dams in Uttarakhand : "+damsInUttarakhand.size());
		
		Collection<String>damsInMaharashtra=new ArrayList<String>();
		damsInMaharashtra.add("Dhampur");
		damsInMaharashtra.add("Vihar");
		damsInMaharashtra.add("Ekrukh");
		damsInMaharashtra.add("Shirsufal");
		damsInMaharashtra.add("Tulshi");
		damsInMaharashtra.add("Khadakwasla");
		damsInMaharashtra.add("Ashti");
		damsInMaharashtra.add("Mhaswad");
		damsInMaharashtra.add("Tansa");
		damsInMaharashtra.add("Shetfal");
		damsInMaharashtra.add("Khairbandha");
		damsInMaharashtra.add("Pahari");
		damsInMaharashtra.add("Rhankapur");
		damsInMaharashtra.add("Ramtek");
		damsInMaharashtra.add("Chandapur");
		damsInMaharashtra.add("Walwan");
		damsInMaharashtra.add("Darna");
		damsInMaharashtra.add("Bodalkasa");
		damsInMaharashtra.add("Psolamendha");
		damsInMaharashtra.add("Shirvata");
		damsInMaharashtra.add("Thokarwadi");
		damsInMaharashtra.add("Chokramara");
		damsInMaharashtra.add("Ghorazari");
		damsInMaharashtra.add("Bhandardara");
		damsInMaharashtra.add("Bhatghar");
		damsInMaharashtra.add("Mulshi");
		damsInMaharashtra.add("Mas");
		damsInMaharashtra.add("Ghanewadi");
		damsInMaharashtra.add("Visapur");
		damsInMaharashtra.add("Radhanagari");
		damsInMaharashtra.add("Vaitarna");
		damsInMaharashtra.add("Purmepeda");
		damsInMaharashtra.add("Khasapur");
		damsInMaharashtra.add("Dheku");
		damsInMaharashtra.add("Sindhapan");
		damsInMaharashtra.add("Ekburji");
		damsInMaharashtra.add("Khelocala");
		damsInMaharashtra.add("UpperDudhana");
		damsInMaharashtra.add("Koyna");
		damsInMaharashtra.add("Ganagapur");
		damsInMaharashtra.add("Chandani");
		damsInMaharashtra.add("Bor");
		damsInMaharashtra.add("Ghod");
		damsInMaharashtra.add("Tisangi");
		damsInMaharashtra.add("Wunna");
		damsInMaharashtra.add("Galhati");
		damsInMaharashtra.add("Mangi");
		damsInMaharashtra.add("Mehakari");
		damsInMaharashtra.add("Wan");
		damsInMaharashtra.add("Bhudihal");
		damsInMaharashtra.add("Nawegaonbandh");
		damsInMaharashtra.add("PandherBodi");
		damsInMaharashtra.add("Kurje");
		damsInMaharashtra.add("Nalganga");
		damsInMaharashtra.add("Anjani");
		damsInMaharashtra.add("Siddeshwar");
		damsInMaharashtra.add("Kundrala");
		damsInMaharashtra.add("Gharni");
		damsInMaharashtra.add("Dolwahal");
		damsInMaharashtra.add("Girna");
		damsInMaharashtra.add("Malangaon");
		damsInMaharashtra.add("Karwand");
		damsInMaharashtra.add("Itiadoh");
		damsInMaharashtra.add("Sirpur");
		damsInMaharashtra.add("Pujaritola");
		damsInMaharashtra.add("Terna");
		damsInMaharashtra.add("Morna");
		damsInMaharashtra.add("Gyanganga");
		damsInMaharashtra.add("UpperPus");
		damsInMaharashtra.add("Malkhed");
		damsInMaharashtra.add("Mula");
		damsInMaharashtra.add("UpperVaitarna");
		damsInMaharashtra.add("Panzara");
		damsInMaharashtra.add("Dina");
		damsInMaharashtra.add("Kanoli");
		damsInMaharashtra.add("Nazare");
		damsInMaharashtra.add("Tiru");
		damsInMaharashtra.add("Dhom");
		System.out.println("Size of dams in Maharashtra : "+damsInMaharashtra.size());
		

		Collection<String>damsInMadhyaPradesh=new ArrayList<String>();
		damsInMadhyaPradesh.add("GandhiSagar");
		damsInMadhyaPradesh.add("IndiraSagar");
		damsInMadhyaPradesh.add("BhakraNangal");
		damsInMadhyaPradesh.add("Bansagar");
		damsInMadhyaPradesh.add("Bargi");
		damsInMadhyaPradesh.add("Tehri");
		damsInMadhyaPradesh.add("Barna");
		damsInMadhyaPradesh.add("Tawa");
		damsInMadhyaPradesh.add("Rajghat");
		damsInMadhyaPradesh.add("Idukki");
		damsInMadhyaPradesh.add("NahapaJakhri");
		damsInMadhyaPradesh.add("Omkareshwar");
		damsInMadhyaPradesh.add("Khadalkwasla");
		damsInMadhyaPradesh.add("Mulshi");
		damsInMadhyaPradesh.add("Rihand");
		damsInMadhyaPradesh.add("Ujani");
		damsInMadhyaPradesh.add("Malampuzha");
		damsInMadhyaPradesh.add("Kundala");
		damsInMadhyaPradesh.add("DumkharHydroeElectric");
		damsInMadhyaPradesh.add("Cheruthoni");
		damsInMadhyaPradesh.add("Madikheda");
		damsInMadhyaPradesh.add("Pawna");
		damsInMadhyaPradesh.add("Gangapur");
		damsInMadhyaPradesh.add("BhadBhada");
		damsInMadhyaPradesh.add("Bheemgarh");
		damsInMadhyaPradesh.add("Dhuty");
		damsInMadhyaPradesh.add("Kutni");
		System.out.println("Size of dams in MadhyaPradesh : "+damsInMadhyaPradesh.size());
		
		
		Collection<String>damsInRajastan=new ArrayList<String>();
		damsInRajastan.add("Bisalpur");
		damsInRajastan.add("JawaharSagar");
		damsInRajastan.add("RanaPratapSagar");
		damsInRajastan.add("Jakham");
		damsInRajastan.add("Jawai");
		damsInRajastan.add("MahiBajajSagar");
		damsInRajastan.add("Tehri");
		damsInRajastan.add("Cheruthoni");
		damsInRajastan.add("KotaBarrage");
		damsInRajastan.add("Gosunda");
		damsInRajastan.add("Sei");
		damsInRajastan.add("SarjuSagr");
		damsInRajastan.add("MansiWakal");
		damsInRajastan.add("Isarda");
		damsInRajastan.add("Jaggar");
		damsInRajastan.add("Kalisindh");
		damsInRajastan.add("Khandip");
		damsInRajastan.add("Morel");
		damsInRajastan.add("Nevta");
		damsInRajastan.add("Parban");
		System.out.println("Size of dams in Rajastan : "+damsInRajastan.size());
		
		Collection<String> damsInUttarPradesh = new ArrayList<String>();
		damsInUttarPradesh.add("Adwa");
		damsInUttarPradesh.add("Afzalgarh");
		damsInUttarPradesh.add("Ahraura");
		damsInUttarPradesh.add("Arjun");
		damsInUttarPradesh.add("Aunjhar");
		damsInUttarPradesh.add("Bachara");
		damsInUttarPradesh.add("Baghel Khand");
		damsInUttarPradesh.add("Baghla");
		damsInUttarPradesh.add("Balui Bandh");
		damsInUttarPradesh.add("Balui");
		damsInUttarPradesh.add("Banjari Kalan");
		damsInUttarPradesh.add("Barwa");
		damsInUttarPradesh.add("Barwa Sagar");
		damsInUttarPradesh.add("Barwar");
		damsInUttarPradesh.add("Barwatola");
		damsInUttarPradesh.add("Bhagwan Pur");
		damsInUttarPradesh.add("Bhainsora");
		damsInUttarPradesh.add("Bhonka");
		damsInUttarPradesh.add("Chandra Prabha");
		damsInUttarPradesh.add("Chandrawal");
		damsInUttarPradesh.add("Chittaurgarh");
		damsInUttarPradesh.add("Deori");
		damsInUttarPradesh.add("Dhandhraul");
		damsInUttarPradesh.add("Dhenkwan");
		damsInUttarPradesh.add("Dongia");
		damsInUttarPradesh.add("pop");
		System.out.println("Size of dams in UttarPradesh : "+damsInUttarPradesh.size());
		
		Collection<String> damsInIndia = new ArrayList<String>();
		damsInIndia.addAll(damsInJammuKashmir);
		damsInIndia.addAll(damsInHimachalPradesh);
		damsInIndia.addAll(damsInPunjab);
		damsInIndia.addAll(damsInHaryana);
		damsInIndia.addAll(damsInUttarakhand);
		damsInIndia.addAll(damsInGujarat);
		damsInIndia.addAll(damsInKarnataka);
		damsInIndia.addAll(damsInKerala);
		damsInIndia.addAll(damsInGoa);
		damsInIndia.addAll(damsInTamilNadu);
		damsInIndia.addAll(damsInTelangana);
		damsInIndia.addAll(damsInChhattisgarh);
		damsInIndia.addAll(damsInArunachalPradesh);
		damsInIndia.addAll(damsInNagaland);
		damsInIndia.addAll(damsInManipur);
		damsInIndia.addAll(damsInMizoram);
		damsInIndia.addAll(damsInAssam);
		damsInIndia.addAll(damsInMeghalaya);
		damsInIndia.addAll(damsInTripura);
		damsInIndia.addAll(damsInWestBengal);
		damsInIndia.addAll(damsInSikkim);
		damsInIndia.addAll(damsInBihar);
		damsInIndia.addAll(damsInJharkhand);
		damsInIndia.addAll(damsInOdisha);
		damsInIndia.addAll(damsInMaharashtra);
		damsInIndia.addAll(damsInMadhyaPradesh);
		damsInIndia.addAll(damsInRajastan);
		damsInIndia.addAll(damsInUttarPradesh);
		
		
		Iterator<String> itr = damsInIndia.iterator();
		while (itr.hasNext()) {
			String element = itr.next();
			if (element.startsWith("T")) {
				System.out.println(element);
			}
		}

		Iterator<String> itr1 = damsInIndia.iterator();
		while (itr1.hasNext()) {
			String element1 = itr1.next();
			if (element1.endsWith("ra")) {
				System.out.println(element1);
			}
		}

		Iterator<String> itr2 = damsInIndia.iterator();
		while (itr2.hasNext()) {
			String element2 = itr2.next();
			if (element2.length() > 15) {
				System.out.println(element2);
			}
		}

		Iterator<String> itr3 = damsInIndia.iterator();
		while (itr3.hasNext()) {
			String element3 = itr3.next();
			System.out.println(element3.toUpperCase());
		}
		
		
		Iterator<String> itr4 = damsInIndia.iterator();
		while (itr4.hasNext()) {
			String element4 = itr4.next();
			System.out.println(element4.toLowerCase());
		}
			
		Iterator<String> remove = damsInIndia.iterator();
		while (remove.hasNext()) {
			String element = remove.next();
			if (element.contains("P"))
				System.out.println("Removing all dams it contains P " + element);
			remove.remove();
		}

		Iterator<String> palindrome = damsInIndia.iterator();
		while (palindrome.hasNext()) {
			String element = (String) palindrome.next();
			StringBuffer buffer = new StringBuffer(element);
			buffer.reverse();
			String reverse = buffer.toString();
			if (element.equalsIgnoreCase(reverse)) {
				System.out.println("Palindrome " + reverse);
			}
		}

	
	}
}
